export { AboutPreview } from "@/components/home/AboutPreview";
export { AchievementsSection, type AchievementItem } from "@/components/home/AchievementsSection";
export { ContactPreview } from "@/components/home/ContactPreview";
export { CoursesPreview, type CoursePreviewItem } from "@/components/home/CoursesPreview";
export { FAQSection, type FAQItem } from "@/components/home/FAQSection";
export { FounderSection } from "@/components/home/FounderSection";
export { GalleryPreview, type GalleryPreviewItem } from "@/components/home/GalleryPreview";
export { Hero } from "@/components/home/Hero";
export { StudentJourney, type JourneyStep } from "@/components/home/StudentJourney";
export { TestimonialsSection, type TestimonialItem } from "@/components/home/TestimonialsSection";
export { TrustStatistics, type TrustStatistic } from "@/components/home/TrustStatistics";
export { WhyChooseUs, type WhyChooseItem } from "@/components/home/WhyChooseUs";
